image: node:16 #tentative

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - node_modules/

.pull_cached_node_modules:
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull

variables:
  PROFILE: "prod" #tentative

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - npm ci
    - npm run build -- -c=${PROFILE}
  artifacts:
    paths:
      - dist/ #tentative. Use angular.json/projects.architect.build.options.outputPath value.
    expire_in: 2 hours

test:
  stage: test
  extends: .pull_cached_node_modules
  before_script:
    - apt-get update
    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt -qq install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script: npm run test-ci
  allow_failure: true
  # tentative
  # artifacts:
  #   when: always
  #   reports:
  #     junit: test-result/*.xml #tentative
  #   expire_in: 1 week

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the default branch (but not in other branch pipelines)

publish:
  stage: publish
  variables:
    PUBLISH_VARIABLE: "prerelease"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        PUBLISH_VARIABLE: "prerelease"
    - if: $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/
      variables:
        PUBLISH_VARIABLE: "release"
  script:
    # If no .npmrc is included in the repo, generate a temporary one that is configured to publish to GitLab's NPM registry
    - |
      if [[ ! -f .npmrc ]]; then
        echo 'No .npmrc found! Creating one now. Please review the following link for more information: https://docs.gitlab.com/ee/user/packages/npm_registry/index.html#project-level-npm-endpoint-1'
        {
          echo "registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
          echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
        } >> .npmrc
      fi
    - echo "Created the following .npmrc:"; cat .npmrc

    # Extract a few values from package.json
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")

    # When building on the default branch, use the prerelease version.
    - |
      if [[ "${PUBLISH_VARIABLE}" == "release" ]]; then
        NPM_PUBLISH_VERSION="${NPM_PACKAGE_VERSION}"
      else
        NPM_PUBLISH_VERSION="${NPM_PACKAGE_VERSION}-rc.${CI_PIPELINE_IID}"
      fi
      echo "Use Version: ${NPM_PUBLISH_VERSION}"

    - npm version "${NPM_PUBLISH_VERSION}" --no-git-tag-version --allow-same-version

    # Compare the version in package.json to all published versions.
    # If the package.json version has not yet been published, run `npm publish`.
    - |
      if [[ $(npm view "${NPM_PACKAGE_NAME}" versions) != *"'${NPM_PUBLISH_VERSION}'"* ]]; then
        npm publish
        echo "Successfully published version ${NPM_PACKAGE_NPM_PUBLISH_VERSIONVERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
      else
        echo "Version ${NPM_PUBLISH_VERSION} of ${NPM_PACKAGE_NAME} has already been published, so no new version has been published."
      fi